apiVersion: apps/v1
kind: Deployment
metadata:
  name: images
spec:
  template:
    spec:
      containers:
      - name: registry
        image: docker.io/mtaylor91/registry:latest
        imagePullPolicy: Always
        env:
        - name: REGISTRY_LOG_LEVEL
          value: debug
        - name: REGISTRY_STORAGE_S3_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: images-s3
              key: access-key
        - name: REGISTRY_STORAGE_S3_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: images-s3
              key: secret-key
        - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
          valueFrom:
            secretKeyRef:
              name: images-s3
              key: s3-endpoint-url
        - name: REGISTRY_STORAGE_S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: images-s3
              key: s3-bucket
        - name: REGISTRY_STORAGE_S3_REGION
          value: auto
