apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
  storageClassName: openebs-lvm-ssdstore
  volumeMode: Filesystem
